  version: "3.8"

services:
  app:
    build: .
    container_name: p-alpha-server
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
    depends_on:
      - db
    # For development, you might mount the source code to auto-reload changes.
    # Uncomment the below volumes if needed:
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - /var/db_data:/var/lib/mysql

volumes:
  /var/db_data:
